<div id="custom-component" data-bind="scope:'customcomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#custom-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponent": {
                        "component": "AHT_FastOrder/js/fast_order"
                    }
                }
            }
        }
    }
    </script>

<div data-block="dropdown" class="minicart-wrapper">
    <button type="button" class="action" data-trigger="trigger">
        <span data-bind="i18n: 'Click Here'"></span>
    </button>
</div>
<div class="block block-minicart"
     data-mage-init='{
        "dropdownDialog": {
            "appendTo": "[data-block=dropdown]",
            "triggerTarget":"[data-trigger=trigger]",
            "timeout": 2000,
            "closeOnMouseLeave": false,
            "closeOnEscape": true,
            "autoOpen": true,
            "triggerClass": "active",
            "parentClass": "active",
            "buttons": [{text: $.mage.__("Close"),click: function () {$("#minicart-content-wrapper").dropdownDialog("close");}]
        }
     }'>
    <div id="minicart-content-wrapper">
        Here is our content
    </div>
</div>
</div>

<!-- <script>
        require([
        'jquery'
        ], function ($) {
            $('.magento__dropdown-widget').dropdown();
        });
        alert('ji');
 </script> -->